### ISSUE TITLE
[Features] 6.流水线相关问题

### ISSUE THREAD

**Issue by shao0099876** [hitwh-nscscc/simple-5stage-pipeline-MIPS-imple#9]
**你的新点子是否关乎到一个文档中存在的问题呢？请描述一下吧！**
以课本描述为基准，该文档中所述“相关”其实是指的“冲突”

**讲一讲你期望的结果**
所有的“相关”改成"冲突"，然后补充一点“相关”的内容

**补充**
相关是指令之间的性质，相关反映了指令之间的依赖性，例如（真）数据相关反映了数据如何从产生的指令流向消费的指令；控制相关反映了指令顺序对分支指令的依赖关系。
冲突是流水线中的现象，指由于指令之间的相关性而使下一条指令不能在指定的时钟周期开始执行，例如硬件资源不足导致的结构冲突

相关是指令之间的性质，是流水线发生冲突现象的原因

**Comment by ArHShRn** [comment]
@RickyTino OPM和教材的描述各不相同，但是在MangoMIPS实现的时候，注释确实又是写的Data Hazard

其中有以下几点不一样
- OPM：数据前推；教材：定向技术
- OPM：数据相关（实则处理的是Data Hazard）；教材：数据相关（dependence），数据冲突（Data Hazard）
  - 其中维基百科上Data Hazard翻译成数据冒险

**Comment by specialpointcentral** [comment]
这个说明很有意思。的确我们可以明确两点：
1. 指令间**相关**和流水线的**相关**是两个不同的概念。可能是翻译的原因，我们把`hazard`有时候翻译成相关。
2. 由于指令间的相关性，会导致流水线的相关性，这种相关性主要表现在冲突上，就是所说的`data hazard`。

当然，为了减少误会，还请 @ArHShRn 修改

敬上

**Comment by specialpointcentral** [comment]
已完成更改，感谢 @ArHShRn 
敬上
